### ISSUE TITLE
大佬，之前的好多分类怎么找不到了？

### ISSUE THREAD

**Issue by Hc7Hs** [lxztju/leetcode-algorithm#2]
大佬，之前的好多分类怎么找不到了？刚按照你的分类做到回溯。。。

**Comment by lxztju** [comment]
请参考v1 tag:  https://github.com/lxztju/leetcode-algorithm/tree/v1

**Comment by Hc7Hs** [comment]
> 请参考v1 tag: https://github.com/lxztju/leetcode-algorithm/tree/v1

感谢大佬
